#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Spla2n_Stuff.Resource", IsApplication=true)]

namespace Spla2n_Stuff
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ModernHttpClient.Resource.String.library_name = global::Spla2n_Stuff.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int cardBackgroundColor = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int cardCornerRadius = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int cardElevation = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int cardMaxElevation = 2130771971;
			
			// aapt resource value: 0x7f010005
			public const int cardPreventCornerOverlap = 2130771973;
			
			// aapt resource value: 0x7f010004
			public const int cardUseCompatPadding = 2130771972;
			
			// aapt resource value: 0x7f010006
			public const int contentPadding = 2130771974;
			
			// aapt resource value: 0x7f01000a
			public const int contentPaddingBottom = 2130771978;
			
			// aapt resource value: 0x7f010007
			public const int contentPaddingLeft = 2130771975;
			
			// aapt resource value: 0x7f010008
			public const int contentPaddingRight = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int contentPaddingTop = 2130771977;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int cardview_dark_background = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int cardview_light_background = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int cardview_shadow_end_color = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int cardview_shadow_start_color = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int theme_devicedefault_background = 2131034116;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060000
			public const int cardview_compat_inset_shadow = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int cardview_default_elevation = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int cardview_default_radius = 2131099650;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int _18k_aviators = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int _52_gal = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int _96_gal = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ability_doubler = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int acerola_rain_boots = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int aerospray_mg = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int aerospray_rg = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int amiibo = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int anchor_life_vest = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int anchor_sweat = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int annaki = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int annaki_beret = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int annaki_drive_tee = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int annaki_evolution_tee = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int annaki_mask = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int armor_boot_replicas = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int armor_helmet_replica = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int armor_jacket_replica = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int arrow_pull_ons = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int autobomb = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int b_ball_jersey__away_ = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int baby_jelly_shirt = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int baby_jelly_shirt___tie = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int backwards_cap = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int baller = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int bamboo_hat = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int basic_tee = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int berry_ski_jacket = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int bike_helmet = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int birch_climbing_shoes = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int birded_corduroy_jacket = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int black_dakroniks = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int black_flip_flops = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int black_inky_rider = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int black_ls = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int black_norimaki_750s = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int black_squideye = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int black_tee = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int black_trainers = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int black_urchin_rock_tee = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int black_v_neck_tee = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int blackbelly_skatepark = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int blaster = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int blowfish_bell_hat = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int blue___black_squidkid_iv = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int blue_moto_boots = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int blue_peaks_tee = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int blue_sailor_suit = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int blue_slip_ons = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int blue_tentatek_tee = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int blueberry_casuals = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int bobble_hat = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int bomb_defense_up = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int bomb_launcher = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int brown_fa_11_bomber = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int bubble_blower = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int bucket_hat = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int burst_bomb = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int camo_mesh = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int camo_zip_hoodie = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int camping_hat = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int canary_trainers = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int carbon_roller = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int cherry_kicks = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int chilly_mountain_coat = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int chirpy_chips_band_tee = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int choco_clogs = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int choco_layered_ls = 2130837571;
			
			// aapt resource value: 0x7f020044
			public const int clash_blaster = 2130837572;
			
			// aapt resource value: 0x7f020045
			public const int cold_blooded = 2130837573;
			
			// aapt resource value: 0x7f020046
			public const int comeback = 2130837574;
			
			// aapt resource value: 0x7f020047
			public const int crazy_arrows = 2130837575;
			
			// aapt resource value: 0x7f020048
			public const int cream_basics = 2130837576;
			
			// aapt resource value: 0x7f020049
			public const int crimson_parashooter = 2130837577;
			
			// aapt resource value: 0x7f02004a
			public const int curling_bomb = 2130837578;
			
			// aapt resource value: 0x7f02004b
			public const int cuttlegear = 2130837579;
			
			// aapt resource value: 0x7f02004c
			public const int cycle_king_cap = 2130837580;
			
			// aapt resource value: 0x7f02004d
			public const int cycle_king_jersey = 2130837581;
			
			// aapt resource value: 0x7f02004e
			public const int dapple_dualies = 2130837582;
			
			// aapt resource value: 0x7f02004f
			public const int dark_urban_vest = 2130837583;
			
			// aapt resource value: 0x7f020050
			public const int drop_roller = 2130837584;
			
			// aapt resource value: 0x7f020051
			public const int dualie_squelchers = 2130837585;
			
			// aapt resource value: 0x7f020052
			public const int dynamo_roller = 2130837586;
			
			// aapt resource value: 0x7f020053
			public const int e_liter_4k = 2130837587;
			
			// aapt resource value: 0x7f020054
			public const int e_liter_4k_scope = 2130837588;
			
			// aapt resource value: 0x7f020055
			public const int eggplant_mountain_coat = 2130837589;
			
			// aapt resource value: 0x7f020056
			public const int enperry = 2130837590;
			
			// aapt resource value: 0x7f020057
			public const int enperry_splat_dualies = 2130837591;
			
			// aapt resource value: 0x7f020058
			public const int fa_01_jacket = 2130837592;
			
			// aapt resource value: 0x7f020059
			public const int fa_01_reversed = 2130837593;
			
			// aapt resource value: 0x7f02005a
			public const int fake_contacts = 2130837594;
			
			// aapt resource value: 0x7f02005b
			public const int fc_albacore = 2130837595;
			
			// aapt resource value: 0x7f02005c
			public const int firefin = 2130837596;
			
			// aapt resource value: 0x7f02005d
			public const int firefin_facemask = 2130837597;
			
			// aapt resource value: 0x7f02005e
			public const int firefin_splat_charger = 2130837598;
			
			// aapt resource value: 0x7f02005f
			public const int firefin_splatterscope = 2130837599;
			
			// aapt resource value: 0x7f020060
			public const int fishfry_visor = 2130837600;
			
			// aapt resource value: 0x7f020061
			public const int five_panel_cap = 2130837601;
			
			// aapt resource value: 0x7f020062
			public const int flingza_roller = 2130837602;
			
			// aapt resource value: 0x7f020063
			public const int forge = 2130837603;
			
			// aapt resource value: 0x7f020064
			public const int fringed_loafers = 2130837604;
			
			// aapt resource value: 0x7f020065
			public const int fugu_tee = 2130837605;
			
			// aapt resource value: 0x7f020066
			public const int gold_hi_horses = 2130837606;
			
			// aapt resource value: 0x7f020067
			public const int goo_tuber = 2130837607;
			
			// aapt resource value: 0x7f020068
			public const int grape_hoodie = 2130837608;
			
			// aapt resource value: 0x7f020069
			public const int gray_8_bit_fishfry = 2130837609;
			
			// aapt resource value: 0x7f02006a
			public const int gray_fa_11_bomber = 2130837610;
			
			// aapt resource value: 0x7f02006b
			public const int gray_hoodie = 2130837611;
			
			// aapt resource value: 0x7f02006c
			public const int gray_sea_slug_hi_tops = 2130837612;
			
			// aapt resource value: 0x7f02006d
			public const int green_check_shirt = 2130837613;
			
			// aapt resource value: 0x7f02006e
			public const int green_tee = 2130837614;
			
			// aapt resource value: 0x7f02006f
			public const int green_v_neck_limited_tee = 2130837615;
			
			// aapt resource value: 0x7f020070
			public const int grizzco = 2130837616;
			
			// aapt resource value: 0x7f020071
			public const int h_3_nozzlenose = 2130837617;
			
			// aapt resource value: 0x7f020072
			public const int half_rim_glasses = 2130837618;
			
			// aapt resource value: 0x7f020073
			public const int half_sleeve_sweater = 2130837619;
			
			// aapt resource value: 0x7f020074
			public const int haunt = 2130837620;
			
			// aapt resource value: 0x7f020075
			public const int headlamp_helmet = 2130837621;
			
			// aapt resource value: 0x7f020076
			public const int heavy_splatling = 2130837622;
			
			// aapt resource value: 0x7f020077
			public const int hero_blaster_replica = 2130837623;
			
			// aapt resource value: 0x7f020078
			public const int hero_charger_replica = 2130837624;
			
			// aapt resource value: 0x7f020079
			public const int hero_dualies_replica = 2130837625;
			
			// aapt resource value: 0x7f02007a
			public const int hero_headphones_replica = 2130837626;
			
			// aapt resource value: 0x7f02007b
			public const int hero_headset_replica = 2130837627;
			
			// aapt resource value: 0x7f02007c
			public const int hero_hoodie_replica = 2130837628;
			
			// aapt resource value: 0x7f02007d
			public const int hero_jacket_replica = 2130837629;
			
			// aapt resource value: 0x7f02007e
			public const int hero_roller_replica = 2130837630;
			
			// aapt resource value: 0x7f02007f
			public const int hero_runner_replicas = 2130837631;
			
			// aapt resource value: 0x7f020080
			public const int hero_shot_replica = 2130837632;
			
			// aapt resource value: 0x7f020081
			public const int hero_slosher_replica = 2130837633;
			
			// aapt resource value: 0x7f020082
			public const int hero_snowboots_replicas = 2130837634;
			
			// aapt resource value: 0x7f020083
			public const int hero_splatling_replica = 2130837635;
			
			// aapt resource value: 0x7f020084
			public const int herobrush_replica = 2130837636;
			
			// aapt resource value: 0x7f020085
			public const int hickory_work_cap = 2130837637;
			
			// aapt resource value: 0x7f020086
			public const int hightide_era_band_tee = 2130837638;
			
			// aapt resource value: 0x7f020087
			public const int hockey_helmet = 2130837639;
			
			// aapt resource value: 0x7f020088
			public const int hula_punk_shirt = 2130837640;
			
			// aapt resource value: 0x7f020089
			public const int humpback_pump_track = 2130837641;
			
			// aapt resource value: 0x7f02008a
			public const int hunter_hi_tops = 2130837642;
			
			// aapt resource value: 0x7f02008b
			public const int hunting_boots = 2130837643;
			
			// aapt resource value: 0x7f02008c
			public const int ic_collections_black_48dp = 2130837644;
			
			// aapt resource value: 0x7f02008d
			public const int ink_armor = 2130837645;
			
			// aapt resource value: 0x7f02008e
			public const int ink_mine = 2130837646;
			
			// aapt resource value: 0x7f02008f
			public const int ink_recovery_up = 2130837647;
			
			// aapt resource value: 0x7f020090
			public const int ink_resistance_up = 2130837648;
			
			// aapt resource value: 0x7f020091
			public const int ink_saver__main_ = 2130837649;
			
			// aapt resource value: 0x7f020092
			public const int ink_saver__sub_ = 2130837650;
			
			// aapt resource value: 0x7f020093
			public const int ink_storm = 2130837651;
			
			// aapt resource value: 0x7f020094
			public const int inkblot_art_academy = 2130837652;
			
			// aapt resource value: 0x7f020095
			public const int inkbrush = 2130837653;
			
			// aapt resource value: 0x7f020096
			public const int inkfall_shirt = 2130837654;
			
			// aapt resource value: 0x7f020097
			public const int inkjet = 2130837655;
			
			// aapt resource value: 0x7f020098
			public const int inkline = 2130837656;
			
			// aapt resource value: 0x7f020099
			public const int inkopolis_squaps_jersey = 2130837657;
			
			// aapt resource value: 0x7f02009a
			public const int jellyvader_cap = 2130837658;
			
			// aapt resource value: 0x7f02009b
			public const int jet_squelcher = 2130837659;
			
			// aapt resource value: 0x7f02009c
			public const int kelp_dome = 2130837660;
			
			// aapt resource value: 0x7f02009d
			public const int kid_clams = 2130837661;
			
			// aapt resource value: 0x7f02009e
			public const int king_facemask = 2130837662;
			
			// aapt resource value: 0x7f02009f
			public const int king_flip_mesh = 2130837663;
			
			// aapt resource value: 0x7f0200a0
			public const int king_jersey = 2130837664;
			
			// aapt resource value: 0x7f0200a1
			public const int knitted_hat = 2130837665;
			
			// aapt resource value: 0x7f0200a2
			public const int krak_on = 2130837666;
			
			// aapt resource value: 0x7f0200a3
			public const int krak_on_splat_roller = 2130837667;
			
			// aapt resource value: 0x7f0200a4
			public const int l_3_nozzlenose = 2130837668;
			
			// aapt resource value: 0x7f0200a5
			public const int last_ditch_effort = 2130837669;
			
			// aapt resource value: 0x7f0200a6
			public const int layered_anchor_ls = 2130837670;
			
			// aapt resource value: 0x7f0200a7
			public const int layered_vector_ls = 2130837671;
			
			// aapt resource value: 0x7f0200a8
			public const int le_soccer_shoes = 2130837672;
			
			// aapt resource value: 0x7f0200a9
			public const int lightweight_cap = 2130837673;
			
			// aapt resource value: 0x7f0200aa
			public const int lime_easy_stripe_shirt = 2130837674;
			
			// aapt resource value: 0x7f0200ab
			public const int loadingicon = 2130837675;
			
			// aapt resource value: 0x7f0200ac
			public const int logo_aloha_shirt = 2130837676;
			
			// aapt resource value: 0x7f0200ad
			public const int luna_blaster = 2130837677;
			
			// aapt resource value: 0x7f0200ae
			public const int MainButtons = 2130837678;
			
			// aapt resource value: 0x7f0200af
			public const int makomart = 2130837679;
			
			// aapt resource value: 0x7f0200b0
			public const int manta_maria = 2130837680;
			
			// aapt resource value: 0x7f0200b1
			public const int matcha_down_jacket = 2130837681;
			
			// aapt resource value: 0x7f0200b2
			public const int mawcasins = 2130837682;
			
			// aapt resource value: 0x7f0200b3
			public const int mini_splatling = 2130837683;
			
			// aapt resource value: 0x7f0200b4
			public const int mint_dakroniks = 2130837684;
			
			// aapt resource value: 0x7f0200b5
			public const int mint_tee = 2130837685;
			
			// aapt resource value: 0x7f0200b6
			public const int mister_shrug_tee = 2130837686;
			
			// aapt resource value: 0x7f0200b7
			public const int moray_towers = 2130837687;
			
			// aapt resource value: 0x7f0200b8
			public const int moto_boots = 2130837688;
			
			// aapt resource value: 0x7f0200b9
			public const int mtb_helmet = 2130837689;
			
			// aapt resource value: 0x7f0200ba
			public const int musselforge_fitness = 2130837690;
			
			// aapt resource value: 0x7f0200bb
			public const int n_zap__85 = 2130837691;
			
			// aapt resource value: 0x7f0200bc
			public const int navy_deca_logo_tee = 2130837692;
			
			// aapt resource value: 0x7f0200bd
			public const int navy_king_tank = 2130837693;
			
			// aapt resource value: 0x7f0200be
			public const int navy_striped_ls = 2130837694;
			
			// aapt resource value: 0x7f0200bf
			public const int negative_longcuff_sweater = 2130837695;
			
			// aapt resource value: 0x7f0200c0
			public const int neon_delta_straps = 2130837696;
			
			// aapt resource value: 0x7f0200c1
			public const int neon_sea_slugs = 2130837697;
			
			// aapt resource value: 0x7f0200c2
			public const int ninja_squid = 2130837698;
			
			// aapt resource value: 0x7f0200c3
			public const int noise_cancelers = 2130837699;
			
			// aapt resource value: 0x7f0200c4
			public const int object_shredder = 2130837700;
			
			// aapt resource value: 0x7f0200c5
			public const int octobowler_shirt = 2130837701;
			
			// aapt resource value: 0x7f0200c6
			public const int octobrush = 2130837702;
			
			// aapt resource value: 0x7f0200c7
			public const int opening_gambit = 2130837703;
			
			// aapt resource value: 0x7f0200c8
			public const int orange_arrows = 2130837704;
			
			// aapt resource value: 0x7f0200c9
			public const int orca_hi_tops = 2130837705;
			
			// aapt resource value: 0x7f0200ca
			public const int oyster_clogs = 2130837706;
			
			// aapt resource value: 0x7f0200cb
			public const int paintball_mask = 2130837707;
			
			// aapt resource value: 0x7f0200cc
			public const int painter_s_mask = 2130837708;
			
			// aapt resource value: 0x7f0200cd
			public const int patched_hat = 2130837709;
			
			// aapt resource value: 0x7f0200ce
			public const int pilot_goggles = 2130837710;
			
			// aapt resource value: 0x7f0200cf
			public const int pink_easy_stripe_shirt = 2130837711;
			
			// aapt resource value: 0x7f0200d0
			public const int pink_trainers = 2130837712;
			
			// aapt resource value: 0x7f0200d1
			public const int piranha_moccasins = 2130837713;
			
			// aapt resource value: 0x7f0200d2
			public const int plum_casuals = 2130837714;
			
			// aapt resource value: 0x7f0200d3
			public const int point_sensor = 2130837715;
			
			// aapt resource value: 0x7f0200d4
			public const int port_mackerel = 2130837716;
			
			// aapt resource value: 0x7f0200d5
			public const int positive_longcuff_sweater = 2130837717;
			
			// aapt resource value: 0x7f0200d6
			public const int power_armor = 2130837718;
			
			// aapt resource value: 0x7f0200d7
			public const int power_armor_mk_i = 2130837719;
			
			// aapt resource value: 0x7f0200d8
			public const int power_boots = 2130837720;
			
			// aapt resource value: 0x7f0200d9
			public const int power_boots_mk_i = 2130837721;
			
			// aapt resource value: 0x7f0200da
			public const int power_mask = 2130837722;
			
			// aapt resource value: 0x7f0200db
			public const int power_mask_mk_i = 2130837723;
			
			// aapt resource value: 0x7f0200dc
			public const int pro_trail_boots = 2130837724;
			
			// aapt resource value: 0x7f0200dd
			public const int prune_parashooter = 2130837725;
			
			// aapt resource value: 0x7f0200de
			public const int pullover_coat = 2130837726;
			
			// aapt resource value: 0x7f0200df
			public const int punk_blacks = 2130837727;
			
			// aapt resource value: 0x7f0200e0
			public const int punk_whites = 2130837728;
			
			// aapt resource value: 0x7f0200e1
			public const int purple_camo_ls = 2130837729;
			
			// aapt resource value: 0x7f0200e2
			public const int purple_hi_horses = 2130837730;
			
			// aapt resource value: 0x7f0200e3
			public const int purple_sea_slugs = 2130837731;
			
			// aapt resource value: 0x7f0200e4
			public const int quick_respawn = 2130837732;
			
			// aapt resource value: 0x7f0200e5
			public const int quick_super_jump = 2130837733;
			
			// aapt resource value: 0x7f0200e6
			public const int rapid_blaster = 2130837734;
			
			// aapt resource value: 0x7f0200e7
			public const int red___black_squidkid_iv = 2130837735;
			
			// aapt resource value: 0x7f0200e8
			public const int red_hi_horses = 2130837736;
			
			// aapt resource value: 0x7f0200e9
			public const int red_mesh_sneakers = 2130837737;
			
			// aapt resource value: 0x7f0200ea
			public const int red_tentatek_tee = 2130837738;
			
			// aapt resource value: 0x7f0200eb
			public const int red_v_neck_limited_tee = 2130837739;
			
			// aapt resource value: 0x7f0200ec
			public const int red_vector_tee = 2130837740;
			
			// aapt resource value: 0x7f0200ed
			public const int reel_sweat = 2130837741;
			
			// aapt resource value: 0x7f0200ee
			public const int respawn_punisher = 2130837742;
			
			// aapt resource value: 0x7f0200ef
			public const int retro_specs = 2130837743;
			
			// aapt resource value: 0x7f0200f0
			public const int retro_sweat = 2130837744;
			
			// aapt resource value: 0x7f0200f1
			public const int roasted_brogues = 2130837745;
			
			// aapt resource value: 0x7f0200f2
			public const int rockenberg = 2130837746;
			
			// aapt resource value: 0x7f0200f3
			public const int run_speed_up = 2130837747;
			
			// aapt resource value: 0x7f0200f4
			public const int safari_hat = 2130837748;
			
			// aapt resource value: 0x7f0200f5
			public const int sailor_stripe_tee = 2130837749;
			
			// aapt resource value: 0x7f0200f6
			public const int samurai_helmet = 2130837750;
			
			// aapt resource value: 0x7f0200f7
			public const int samurai_jacket = 2130837751;
			
			// aapt resource value: 0x7f0200f8
			public const int samurai_shoes = 2130837752;
			
			// aapt resource value: 0x7f0200f9
			public const int school_cardigan = 2130837753;
			
			// aapt resource value: 0x7f0200fa
			public const int school_shoes = 2130837754;
			
			// aapt resource value: 0x7f0200fb
			public const int school_uniform = 2130837755;
			
			// aapt resource value: 0x7f0200fc
			public const int shellendorf_institute = 2130837756;
			
			// aapt resource value: 0x7f0200fd
			public const int shifty_station = 2130837757;
			
			// aapt resource value: 0x7f0200fe
			public const int shirt___tie = 2130837758;
			
			// aapt resource value: 0x7f0200ff
			public const int shirt_with_blue_hoodie = 2130837759;
			
			// aapt resource value: 0x7f020100
			public const int short_knit_layers = 2130837760;
			
			// aapt resource value: 0x7f020101
			public const int shrimp_pink_polo = 2130837761;
			
			// aapt resource value: 0x7f020102
			public const int skalop = 2130837762;
			
			// aapt resource value: 0x7f020103
			public const int skull_bandana = 2130837763;
			
			// aapt resource value: 0x7f020104
			public const int slash_king_tank = 2130837764;
			
			// aapt resource value: 0x7f020105
			public const int slipstream_united = 2130837765;
			
			// aapt resource value: 0x7f020106
			public const int slosher = 2130837766;
			
			// aapt resource value: 0x7f020107
			public const int smoky_wingtips = 2130837767;
			
			// aapt resource value: 0x7f020108
			public const int snapper_canal = 2130837768;
			
			// aapt resource value: 0x7f020109
			public const int snorkel_mask = 2130837769;
			
			// aapt resource value: 0x7f02010a
			public const int snow_delta_straps = 2130837770;
			
			// aapt resource value: 0x7f02010b
			public const int soccer_headband = 2130837771;
			
			// aapt resource value: 0x7f02010c
			public const int special_charge_up = 2130837772;
			
			// aapt resource value: 0x7f02010d
			public const int special_forces_beret = 2130837773;
			
			// aapt resource value: 0x7f02010e
			public const int special_power_up = 2130837774;
			
			// aapt resource value: 0x7f02010f
			public const int special_saver = 2130837775;
			
			// aapt resource value: 0x7f020110
			public const int splash_mob = 2130837776;
			
			// aapt resource value: 0x7f020111
			public const int splash_o_matic = 2130837777;
			
			// aapt resource value: 0x7f020112
			public const int splash_wall = 2130837778;
			
			// aapt resource value: 0x7f020113
			public const int splashdown = 2130837779;
			
			// aapt resource value: 0x7f020114
			public const int splat_bomb = 2130837780;
			
			// aapt resource value: 0x7f020115
			public const int splat_brella = 2130837781;
			
			// aapt resource value: 0x7f020116
			public const int splat_charger = 2130837782;
			
			// aapt resource value: 0x7f020117
			public const int splat_dualies = 2130837783;
			
			// aapt resource value: 0x7f020118
			public const int splat_roller = 2130837784;
			
			// aapt resource value: 0x7f020119
			public const int splatfest_tee = 2130837785;
			
			// aapt resource value: 0x7f02011a
			public const int splatterscope = 2130837786;
			
			// aapt resource value: 0x7f02011b
			public const int splattershot = 2130837787;
			
			// aapt resource value: 0x7f02011c
			public const int splattershot_jr_ = 2130837788;
			
			// aapt resource value: 0x7f02011d
			public const int splattershot_pro = 2130837789;
			
			// aapt resource value: 0x7f02011e
			public const int sploosh_o_matic = 2130837790;
			
			// aapt resource value: 0x7f02011f
			public const int sprinkler = 2130837791;
			
			// aapt resource value: 0x7f020120
			public const int squash_headband = 2130837792;
			
			// aapt resource value: 0x7f020121
			public const int squid_beakon = 2130837793;
			
			// aapt resource value: 0x7f020122
			public const int squid_clip_ons = 2130837794;
			
			// aapt resource value: 0x7f020123
			public const int squid_facemask = 2130837795;
			
			// aapt resource value: 0x7f020124
			public const int squid_hairclip = 2130837796;
			
			// aapt resource value: 0x7f020125
			public const int squid_satin_jacket = 2130837797;
			
			// aapt resource value: 0x7f020126
			public const int squid_squad_band_tee = 2130837798;
			
			// aapt resource value: 0x7f020127
			public const int squiddor_polo = 2130837799;
			
			// aapt resource value: 0x7f020128
			public const int squidfin_hook_cans = 2130837800;
			
			// aapt resource value: 0x7f020129
			public const int squidforce = 2130837801;
			
			// aapt resource value: 0x7f02012a
			public const int squidvader_cap = 2130837802;
			
			// aapt resource value: 0x7f02012b
			public const int squinja_boots = 2130837803;
			
			// aapt resource value: 0x7f02012c
			public const int squinja_mask = 2130837804;
			
			// aapt resource value: 0x7f02012d
			public const int squinja_suit = 2130837805;
			
			// aapt resource value: 0x7f02012e
			public const int starfish_mainstage = 2130837806;
			
			// aapt resource value: 0x7f02012f
			public const int stealth_jump = 2130837807;
			
			// aapt resource value: 0x7f020130
			public const int sting_ray = 2130837808;
			
			// aapt resource value: 0x7f020131
			public const int straping_whites = 2130837809;
			
			// aapt resource value: 0x7f020132
			public const int strapping_reds = 2130837810;
			
			// aapt resource value: 0x7f020133
			public const int straw_boater = 2130837811;
			
			// aapt resource value: 0x7f020134
			public const int striped_beanie = 2130837812;
			
			// aapt resource value: 0x7f020135
			public const int studio_headphones = 2130837813;
			
			// aapt resource value: 0x7f020136
			public const int sturgeon_shipyard = 2130837814;
			
			// aapt resource value: 0x7f020137
			public const int sub_power_up = 2130837815;
			
			// aapt resource value: 0x7f020138
			public const int suction_bomb = 2130837816;
			
			// aapt resource value: 0x7f020139
			public const int sun_visor = 2130837817;
			
			// aapt resource value: 0x7f02013a
			public const int sunny_climbing_shoes = 2130837818;
			
			// aapt resource value: 0x7f02013b
			public const int sunny_day_tee = 2130837819;
			
			// aapt resource value: 0x7f02013c
			public const int sunset_orca_hi_tops = 2130837820;
			
			// aapt resource value: 0x7f02013d
			public const int swim_speed_up = 2130837821;
			
			// aapt resource value: 0x7f02013e
			public const int takoroka = 2130837822;
			
			// aapt resource value: 0x7f02013f
			public const int takoroka_mesh = 2130837823;
			
			// aapt resource value: 0x7f020140
			public const int takoroka_visor = 2130837824;
			
			// aapt resource value: 0x7f020141
			public const int takoroka_windcrusher = 2130837825;
			
			// aapt resource value: 0x7f020142
			public const int tenacity = 2130837826;
			
			// aapt resource value: 0x7f020143
			public const int tennis_headband = 2130837827;
			
			// aapt resource value: 0x7f020144
			public const int tenta_missiles = 2130837828;
			
			// aapt resource value: 0x7f020145
			public const int tentatek = 2130837829;
			
			// aapt resource value: 0x7f020146
			public const int tentatek_splattershot = 2130837830;
			
			// aapt resource value: 0x7f020147
			public const int the_reef = 2130837831;
			
			// aapt resource value: 0x7f020148
			public const int thermal_ink = 2130837832;
			
			// aapt resource value: 0x7f020149
			public const int tinted_shades = 2130837833;
			
			// aapt resource value: 0x7f02014a
			public const int toni_kensa = 2130837834;
			
			// aapt resource value: 0x7f02014b
			public const int toxic_mist = 2130837835;
			
			// aapt resource value: 0x7f02014c
			public const int trail_boots = 2130837836;
			
			// aapt resource value: 0x7f02014d
			public const int tri_slosher = 2130837837;
			
			// aapt resource value: 0x7f02014e
			public const int urchins_cap = 2130837838;
			
			// aapt resource value: 0x7f02014f
			public const int urchins_jersey = 2130837839;
			
			// aapt resource value: 0x7f020150
			public const int varsity_jacket = 2130837840;
			
			// aapt resource value: 0x7f020151
			public const int vintage_check_shirt = 2130837841;
			
			// aapt resource value: 0x7f020152
			public const int visor_skate_helmet = 2130837842;
			
			// aapt resource value: 0x7f020153
			public const int walleye_warehouse = 2130837843;
			
			// aapt resource value: 0x7f020154
			public const int wet_floor_band_tee = 2130837844;
			
			// aapt resource value: 0x7f020155
			public const int white_8_bit_fishfry = 2130837845;
			
			// aapt resource value: 0x7f020156
			public const int white_anchor_tee = 2130837846;
			
			// aapt resource value: 0x7f020157
			public const int white_baseball_ls = 2130837847;
			
			// aapt resource value: 0x7f020158
			public const int white_deca_logo_tee = 2130837848;
			
			// aapt resource value: 0x7f020159
			public const int white_headband = 2130837849;
			
			// aapt resource value: 0x7f02015a
			public const int white_inky_rider = 2130837850;
			
			// aapt resource value: 0x7f02015b
			public const int white_kicks = 2130837851;
			
			// aapt resource value: 0x7f02015c
			public const int white_king_tank = 2130837852;
			
			// aapt resource value: 0x7f02015d
			public const int white_norimaki_750s = 2130837853;
			
			// aapt resource value: 0x7f02015e
			public const int white_seahorses = 2130837854;
			
			// aapt resource value: 0x7f02015f
			public const int white_tee = 2130837855;
			
			// aapt resource value: 0x7f020160
			public const int white_urchin_rock_tee = 2130837856;
			
			// aapt resource value: 0x7f020161
			public const int white_v_neck_tee = 2130837857;
			
			// aapt resource value: 0x7f020162
			public const int yellow_layered_ls = 2130837858;
			
			// aapt resource value: 0x7f020163
			public const int yellow_mesh_sneakers = 2130837859;
			
			// aapt resource value: 0x7f020164
			public const int yellow_urban_vest = 2130837860;
			
			// aapt resource value: 0x7f020165
			public const int zekko = 2130837861;
			
			// aapt resource value: 0x7f020166
			public const int zekko_baseball_ls = 2130837862;
			
			// aapt resource value: 0x7f020167
			public const int zekko_hoodie = 2130837863;
			
			// aapt resource value: 0x7f020168
			public const int zekko_jade_coat = 2130837864;
			
			// aapt resource value: 0x7f020169
			public const int zekko_redleaf_coat = 2130837865;
			
			// aapt resource value: 0x7f02016a
			public const int zink = 2130837866;
			
			// aapt resource value: 0x7f02016b
			public const int zink_layered_ls = 2130837867;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080020
			public const int abilityButton = 2131230752;
			
			// aapt resource value: 0x7f080003
			public const int abilityDescription = 2131230723;
			
			// aapt resource value: 0x7f080000
			public const int abilityListView = 2131230720;
			
			// aapt resource value: 0x7f080002
			public const int abilityTitle = 2131230722;
			
			// aapt resource value: 0x7f080021
			public const int brandButton = 2131230753;
			
			// aapt resource value: 0x7f08000d
			public const int brandName = 2131230733;
			
			// aapt resource value: 0x7f080004
			public const int brandTitle = 2131230724;
			
			// aapt resource value: 0x7f080023
			public const int clothingButton = 2131230755;
			
			// aapt resource value: 0x7f080007
			public const int commonDescription = 2131230727;
			
			// aapt resource value: 0x7f080005
			public const int commonTitle = 2131230725;
			
			// aapt resource value: 0x7f08000b
			public const int gearTitle = 2131230731;
			
			// aapt resource value: 0x7f080022
			public const int headgearButton = 2131230754;
			
			// aapt resource value: 0x7f08000c
			public const int imageBrand = 2131230732;
			
			// aapt resource value: 0x7f080006
			public const int imageCommon = 2131230726;
			
			// aapt resource value: 0x7f08002d
			public const int imageSpecial = 2131230765;
			
			// aapt resource value: 0x7f08002a
			public const int imageSub = 2131230762;
			
			// aapt resource value: 0x7f080009
			public const int imageUncommon = 2131230729;
			
			// aapt resource value: 0x7f080001
			public const int imageView1 = 2131230721;
			
			// aapt resource value: 0x7f08001e
			public const int league1Image = 2131230750;
			
			// aapt resource value: 0x7f08001c
			public const int league1Name = 2131230748;
			
			// aapt resource value: 0x7f08001f
			public const int league2Image = 2131230751;
			
			// aapt resource value: 0x7f08001d
			public const int league2Name = 2131230749;
			
			// aapt resource value: 0x7f08001b
			public const int leagueModeDesc = 2131230747;
			
			// aapt resource value: 0x7f08001a
			public const int leagueModeTitle = 2131230746;
			
			// aapt resource value: 0x7f080018
			public const int ranked1Image = 2131230744;
			
			// aapt resource value: 0x7f080016
			public const int ranked1Name = 2131230742;
			
			// aapt resource value: 0x7f080019
			public const int ranked2Image = 2131230745;
			
			// aapt resource value: 0x7f080017
			public const int ranked2Name = 2131230743;
			
			// aapt resource value: 0x7f080015
			public const int rankedModeDesc = 2131230741;
			
			// aapt resource value: 0x7f080014
			public const int rankedModeTitle = 2131230740;
			
			// aapt resource value: 0x7f080012
			public const int regular1Image = 2131230738;
			
			// aapt resource value: 0x7f080010
			public const int regular1Name = 2131230736;
			
			// aapt resource value: 0x7f080013
			public const int regular2Image = 2131230739;
			
			// aapt resource value: 0x7f080011
			public const int regular2Name = 2131230737;
			
			// aapt resource value: 0x7f08000f
			public const int regularModeDesc = 2131230735;
			
			// aapt resource value: 0x7f08000e
			public const int regularModeTitle = 2131230734;
			
			// aapt resource value: 0x7f080024
			public const int shoesButton = 2131230756;
			
			// aapt resource value: 0x7f08002e
			public const int specialDescription = 2131230766;
			
			// aapt resource value: 0x7f08002c
			public const int specialTitle = 2131230764;
			
			// aapt resource value: 0x7f080025
			public const int specialsButton = 2131230757;
			
			// aapt resource value: 0x7f08002f
			public const int stats = 2131230767;
			
			// aapt resource value: 0x7f080027
			public const int subButton = 2131230759;
			
			// aapt resource value: 0x7f08002b
			public const int subDescription = 2131230763;
			
			// aapt resource value: 0x7f080029
			public const int subTitle = 2131230761;
			
			// aapt resource value: 0x7f08000a
			public const int uncommonDescription = 2131230730;
			
			// aapt resource value: 0x7f080008
			public const int uncommonTitle = 2131230728;
			
			// aapt resource value: 0x7f080028
			public const int weaponTitle = 2131230760;
			
			// aapt resource value: 0x7f080026
			public const int weaponsButton = 2131230758;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Ability = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Ability_List = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Brand_Layout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Gear_Layout = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Weapon_Layout = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070001
			public const int app_name = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int library_name = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int loadingText = 2131165186;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f040001
			public const int Base_CardView = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int CardView = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int CardView_Dark = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int CardView_Light = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int Theme_Custom = 2130968580;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] CardView = new int[] {
					16843071,
					16843072,
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978};
			
			// aapt resource value: 1
			public const int CardView_android_minHeight = 1;
			
			// aapt resource value: 0
			public const int CardView_android_minWidth = 0;
			
			// aapt resource value: 2
			public const int CardView_cardBackgroundColor = 2;
			
			// aapt resource value: 3
			public const int CardView_cardCornerRadius = 3;
			
			// aapt resource value: 4
			public const int CardView_cardElevation = 4;
			
			// aapt resource value: 5
			public const int CardView_cardMaxElevation = 5;
			
			// aapt resource value: 7
			public const int CardView_cardPreventCornerOverlap = 7;
			
			// aapt resource value: 6
			public const int CardView_cardUseCompatPadding = 6;
			
			// aapt resource value: 8
			public const int CardView_contentPadding = 8;
			
			// aapt resource value: 12
			public const int CardView_contentPaddingBottom = 12;
			
			// aapt resource value: 9
			public const int CardView_contentPaddingLeft = 9;
			
			// aapt resource value: 10
			public const int CardView_contentPaddingRight = 10;
			
			// aapt resource value: 11
			public const int CardView_contentPaddingTop = 11;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
